// <auto-generated />
using System;
using AdessoRideShare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdessoRideShare.Migrations
{
    [DbContext(typeof(RideShareDbContext))]
    [Migration("20250705190909_UpdateCityGridCoordinates")]
    partial class UpdateCityGridCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdessoRideShare.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GridX")
                        .HasColumnType("int");

                    b.Property<int>("GridY")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GridX = 2,
                            GridY = 8,
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = 2,
                            GridX = 10,
                            GridY = 5,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 3,
                            GridX = 6,
                            GridY = 2,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 4,
                            GridX = 3,
                            GridY = 7,
                            Name = "Manisa"
                        },
                        new
                        {
                            Id = 5,
                            GridX = 5,
                            GridY = 6,
                            Name = "Uşak"
                        },
                        new
                        {
                            Id = 6,
                            GridX = 8,
                            GridY = 6,
                            Name = "Afyon"
                        },
                        new
                        {
                            Id = 7,
                            GridX = 9,
                            GridY = 4,
                            Name = "Eskişehir"
                        },
                        new
                        {
                            Id = 8,
                            GridX = 5,
                            GridY = 3,
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = 9,
                            GridX = 6,
                            GridY = 5,
                            Name = "Kütahya"
                        },
                        new
                        {
                            Id = 10,
                            GridX = 4,
                            GridY = 4,
                            Name = "Balıkesir"
                        },
                        new
                        {
                            Id = 11,
                            GridX = 7,
                            GridY = 1,
                            Name = "Kocaeli"
                        },
                        new
                        {
                            Id = 12,
                            GridX = 8,
                            GridY = 2,
                            Name = "Sakarya"
                        },
                        new
                        {
                            Id = 13,
                            GridX = 4,
                            GridY = 8,
                            Name = "Denizli"
                        },
                        new
                        {
                            Id = 14,
                            GridX = 12,
                            GridY = 7,
                            Name = "Konya"
                        },
                        new
                        {
                            Id = 15,
                            GridX = 8,
                            GridY = 9,
                            Name = "Antalya"
                        });
                });

            modelBuilder.Entity("AdessoRideShare.Models.TravelPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromCityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("ToCityId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromCityId");

                    b.HasIndex("ToCityId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelPlans");
                });

            modelBuilder.Entity("AdessoRideShare.Models.TravelRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TravelPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TravelPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelRequests");
                });

            modelBuilder.Entity("AdessoRideShare.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Email = "test@adesso.com",
                            FullName = "Test Kullanıcı",
                            PasswordHash = "hashedpassword"
                        });
                });

            modelBuilder.Entity("AdessoRideShare.Models.TravelPlan", b =>
                {
                    b.HasOne("AdessoRideShare.Models.City", "FromCity")
                        .WithMany()
                        .HasForeignKey("FromCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdessoRideShare.Models.City", "ToCity")
                        .WithMany()
                        .HasForeignKey("ToCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdessoRideShare.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdessoRideShare.Models.TravelRequest", b =>
                {
                    b.HasOne("AdessoRideShare.Models.TravelPlan", "TravelPlan")
                        .WithMany()
                        .HasForeignKey("TravelPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdessoRideShare.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TravelPlan");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
